### ISSUE TITLE
#2616. 20170111. JAMP. Control de acceso en WEB de Configuracion Remota

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#11]
Solo un usuario puede acceder simultaneamente a la aplicacion.
Los intentos de acceso, estando logeado un usuario deben rechazarse informando de quien está logeado.

**Comment by Senttencya** [comment]
Se ha añadido el control de acceso en la aplicación. Hay que probarlo desde diferentes equipos y en diferentes condiciones.

**Comment by agluque62** [comment]
Rechaza entrada en sesión, pero indica el usuario que está intentando el acceso

**Comment by Senttencya** [comment]
Ya indica el usuario
