### ISSUE TITLE
#2618. 20170111. JAMP. Perfiles

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#12]
Implementar los controles acceso según la 'ultima especificación', generada por ING.

**Comment by Senttencya** [comment]
La gestión de perfiles funciona dependiendo de los privilegios que se otorguen a cada usuario.

**Comment by agluque62** [comment]
Esta repetida. Dejo abierta #2618

**Comment by agluque62** [comment]
Al cambiar items del nivel de acceso de usuarios, la herramienta de Configuración Centralizada debe modificar la "fecha" de la BD, para que el RCS2010 sea consciente de posibles cambios.
