### ISSUE TITLE
#2673. Históricos: NO se presenta en la exportación todos los filtros aplicados

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#13]
Al verificar #2603 (relacionada con Estadísticas), y realizar posteriormente la misma comprobación con Históricos, NO se presenta en la exportación todos los filtros aplicados; por ejemplo, al aplicar "Todas las Alarmas" no se presenta este campo en el fichero de exportación.

**Comment by Senttencya** [comment]
Funciona correctamente, solo que a mi me abre dos pestañas para exportar, pero los filtros aparecen correctos, en principio.

**Comment by agluque62** [comment]
a) al hacer una consulta "Grupo Seguridad" + "Fecha Hora", solo presenta "Grupo Seguridad"
b) Al hacer una consulta sin filtro (Todos) con un resultado de 150 páginas, al seleccionar .pdf, se produce un bucle de pestañas en el navegador, y no presenta el resultado.

**Comment by Senttencya** [comment]
a funciona para grupo… Falta para componente y Evento, que me parece que no funciona ni el SELECT

**Comment by Senttencya** [comment]
Arreglado todos los filtros para los históricos. Falta el detalle de eliminar dos columnas vacías al exportar el pdf de los eventos, ya que tiene dos columnas menos.

**Comment by Senttencya** [comment]
Estadísticas parece que 'a priori' funciona.

FALTA: quitar el NaN de algunas cadenas de texto.

**Comment by agluque62** [comment]
Al ejecutar una consulta con "Todas las Alarmas", en la que había registros de los días 24/03 al 28/03, sólo presenta en el .pdf registros del día 24/03, y salen varias pestañas en el navegador
