### ISSUE TITLE
#2683. Listas B/N. Selección de restricción única

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#15]
Listas B/N. Se debe poder activar la Restricción seleccionada por el usuario en las listas B/N de un recurso radio remoto, entre una de las opciones: Lista Blanca, Lista Negra o None.
Esto no entra en contradicción para permitir editar la lista Blanca y Negra de un recurso, pero sólo puede estar activa una de las restricciones anteriormente indicadas.

**Comment by Senttencya** [comment]
Parece que funciona bien y se ha retocado un poco los textos y la visualización

**Comment by agluque62** [comment]
Tras aplicar la configuración, al volver al recurso no presenta la restricción seleccionada

**Comment by Senttencya** [comment]
Ya se selecciona el tipo de lista por defecto y se cargan las URIs asignadas
