### ISSUE TITLE
#2685. Grabación de recursos radio pasarela, solo debe permitirse para Remoto Rx y Remoto RxTx

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#16]
Edición de Recursos tipo Radio. Al acceder a /Configuración/Emplazamientos/Pasarelas/Slot:x Interfaz:y/pestaña Radio de un recurso Radio Tipo "Local FD-P/R", permite la selección de "Habilita grabación" => Eliminar esta opción de TODOS los tipos de recursos, manteniéndola exclusivamente para los recursos radio tipo "Remoto Rx" y "Remoto Rx Tx".
Nota: Al seleccionar en el desplegable "Tipo de Agente Radio" una opción "Local xxx" desaparece el control "Habilita grabación"

**Comment by Senttencya** [comment]
Cambiado tanto el comportamiento como la selección inicial de este campo. Ahora solo aparece si se seleccionan las dos opciones mencionadas.
