### ISSUE TITLE
#2693. Al modificar una propiedad de la plantilla SERVICIOS sobre una pasarela, al aplicar cambios solo se comunica a la pasarela que se estaba editando

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#18]
Al modificar una propiedad de la plantilla SERVICIOS sobre una pasarela, al aplicar cambios solo se comunica a la pasarela que se estaba editando, cuando al ser una modificación en la plantilla de SERVICIOS debería aplicarse los cambios a todas las pasarelas afectadas por la plantilla modificada. Propuesta:
a) Hacer que afecte a todas las pasarelas o
b) eliminar el item plantilla de servicios.

**Comment by Senttencya** [comment]
Probar con varias pasarelas en el lab

**Comment by Senttencya** [comment]
Se ha cambiado lo de las plantillas y ya no tiene sentido.
