### ISSUE TITLE
#2706. La herramienta de CONFIG_CENTRAL, no consolida cambios Interfaz Grabador "IP SERVIDOR RTSP (A)" y "PUERTO SERVIDOR RTSP" realizados desde CONF_LOCAL

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#19]
Desde la herramienta de CONFIG_LOCAL editamos en Interfaz Grabador "IP SERVIDOR RTSP (A)" y "PUERTO SERVIDOR RTSP" y subimos los cambios.
La herramienta de CONFIG_CENTRAL, no consolida estos cambios, y mantiene los valores anteriores, de forma que al difundir la configuración a las pasarelas sobreescribe/borra los valores introducidos desde CONF_LOCAL.

**Comment by agluque62** [comment]
Idem a la 2707...

**Comment by Senttencya** [comment]
Corregida comprobando que si se manda en el set de datos el campo rtspb_ip, se elimina para poder hacer el INSERT correctamente.
