### ISSUE TITLE
#2707. La herramienta de CONFIG_CENTRAL, no consolida cambios en Agente SNMP "Destinos TRAPS" realizados desde CONF_LOCAL

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#20]
Desde la herramienta de CONFIG_LOCAL editamos en Agente SNMP "Destinos TRAPS" y subimos los cambios.
La herramienta de CONFIG_CENTRAL, no consolida estos cambios, y mantiene los valores anteriores, de forma que al difundir la configuración a las pasarelaa sobreescribe/borra los valores introducidos desde CONF_LOCAL.
Revisar comportamiento con resto de campos editables de esta pestaña: "Puerto SNMP", "SNMP-V2?" y "SNMP-V2-COMMUNITY"

**Comment by agluque62** [comment]
Vamos a modificar la estructura de asignacion de estos parámetros en la base de datos.

**Comment by Senttencya** [comment]
Al corregir la 2706 se ha corregido esta también.

Mencionar que aparece un error que no consigo encontrar:
Error in asynchronous PUT. ER_BAD_FIELD_ERROR: Unknown column 'acGrupoMulticast' in 'field list'
Aunque parece que todo se está actualizando correctamente. A tener en cuenta
