### ISSUE TITLE
LOCAL-0001. Cambio en Fichero de Intercambio REDAN

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#21]
Nuevo campo en el fichero de intercambio REDAN:

Fichero de Intercambio REDAN (JSON):

	Localización:  ROOT.servicios,grab.rtspb_ip
	Carácter: Obligatorio.
	Valores: STRING Vacio (por defecto) o Formato IP V4

Este parámetro, y hasta que se diga lo contrario, no se presentará en los editores correspondientes de REDAN, tanto en local como en remoto.

**Comment by Senttencya** [comment]
Ignorado desde el servidor
