### ISSUE TITLE
#2793. Recurso tipo PP-BC: parámetros relacionados con VOX

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#25]
En la pestaña de Telefonia de un Recurso de Pasarela TIPO PP-BC, se presentan los campos de Activación de VOX, Nivel Umbral de VOX y tiempo de cola VOX.
Estos campos SÓLO están definidos en Config.LOCAL para recursos del tipo PP-BL. 
REVISAR, de forma que en ambas herramientas aparezcan los mismos campos/campos necesarios.

**Comment by Senttencya** [comment]
Eliminadas las opciones Vox para Recurso tipo PP-BC
