### ISSUE TITLE
#2803	Procedimiento de aviso a RCS2010 para reiniciar supervisión al cambiar de emplazamiento una pasarela

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#26]
Arrastrar y Soltar una Pasarela de un emplazamiento a otro emplazamiento incluido de la configuración activa, debe FORZAR Mensaje en RCS de reabrir el aplicativo para cargar la nueva CONFIGURACIÓN.
Se ha comprobado que sin utiliza el botón APLICAR CAMBIOS se ha distribuido a las pasarelas su nueva INFO de emplazamiento. ????

**Comment by Senttencya** [comment]
El cambio de emplazamiento ya se guarda correctamente en BBDD por tanto la transmisión de este a la pasarela debe de producirse si problemas.

**Comment by Senttencya** [comment]
Comprobar que al cambiar de emplazamiento no cambia la fecha de activación de la configuración.
Y si es el antiguo cambio de emplazamiento el que da los problemas, quitar el drag.

**Comment by Senttencya** [comment]
Quitado el drag y no cambia la fecha. Quizás haya que implementar algún mecanismo para comunicar mantenimiento con configuración.
