### ISSUE TITLE
#2802. Aumentar espacio reservado al campo que muestra las URI's disponibles + Presentar <resourceName@IP:port>

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#27]
El espacio reservado al campo que muestra las URI's disponibles parece demasiado pequeño para mostrar una URI completa.
LOS TEXTOS en gris que invitan a escribir una URI aparecen tal que <resourceName@IP> en gris --> debería presentar <resourceName@IP:port> se asume que es PROTOCOLO UDP

**Comment by Senttencya** [comment]
Modificado y adaptado
