### ISSUE TITLE
#2813. Homogeneizar web-page de los recursos entre web-pages de herramientas LOCAL-CENTRALIZADA

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#30]
Homogeneizar web-page de los recursos entre web-pages de herramientas LOCAL-CENTRALIZADA; p.e.
1) El tipo codec que aparece en la solapa/recuadro general del recurso en Config-Centralizada no viene mucho al caso, porque p.e. al ser obligatorio dar soporte a los dos codecs A-Law y u-Law, y al permitir sesiones múltiples, pude darse el caso que un colateral nos abra sesión con un codec u-Law y otro con A-Law etc...
2) El campo SIP URI propia del recurso, ha desaparecido o nunca ha existido en Configuración Centralizada. 
3) El puerto SIP podría ser necesario dejarlo CONFIGURABLE para toda la pasarela.
4) Al arrastrar y soltar un recurso en la estructura HW de la pasarela en Configuración Centralizada, NO PIDE CONFIRMACIÓN. Puede ser peligroso si se hace sin darnos cuenta.

**Comment by Senttencya** [comment]
Punto 4 por ahora

**Comment by Senttencya** [comment]
Punto 2 hecho. Los otros dos no son aplicables.

**Comment by agluque62** [comment]
Impedir drag&drop de pasarelas de otras configuraciones

**Comment by Senttencya** [comment]
Deshabilitado el drag&drop que quedaba
