### ISSUE TITLE
#2826  Tras pulsar el boton ELIMINAR, se echa de menos una ventana de CONFIRMACION

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#32]
Tras pulsar el boton ELIMINAR, se echa de menos una ventana de CONFIRMACION.
NOTA: En función de la relevancia de lo que se vaya a eliminar, podría ser necesario, pedir la password del usuario que inició la sesión.

**Comment by Senttencya** [comment]
Las opciones: "Eliminar Configuración", "Eliminar Emplazamiento", "Eliminar Pasarela" y "Eliminar Recurso" tienen un cuadro de diálogo para advertir y confirmar/cancelar. Si es necesario en mas acciones, por favor especificar en cuál. En el caso de requerir password indicad también cuáles.
