### ISSUE TITLE
#2825  La herramienta permite Asignar nombres de configuraciones existentes a COPIAS de la configuración, y a NUEVAS_CONFIGURACIONES

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#33]
La herramienta permite Asignar nombres de configuraciones existentes a COPIAS de la configuración, y a NUEVAS_CONFIGURACIONES.
Al hacer esto último, directamente le asigna todos los emplazamientos y pasarelas que encuentren dentro de la Configuración copiada, conservando el campo descripción recién creado

**Comment by Senttencya** [comment]
Nombres de configuraciones no pueden ser repetidos

**Comment by Senttencya** [comment]
Parece que ya funciona. Comprueba el nombre tanto en una nueva como en la copia de la existente para no crear duplicados... Ojo que al duplicarla hace algo raro creándola pero parece que todo está correcto.
