### ISSUE TITLE
#2824  En la solapa GENERAL de una pasarela aparece el campo EMPLAZAMIENTO, pero el contenido del campo INCLUYE como prefijo el nombre de la Configuración ¿?

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#34]
En la solapa GENERAL de una pasarela aparece el campo EMPLAZAMIENTO, pero el contenido del campo INCLUYE como prefijo el nombre de la Configuración ¿?

**Comment by Senttencya** [comment]
Está puesto el nombre: "CONFIGURACION-EMPLAZAMIENTO" porque ese selector no solo indica dónde se encuentra configurada la pasarela, sino también poder cambiarla de ubicación en la configuración. Por tanto aparecen los emplazamientos con los nombres de las configuraciones a las que pertenecen por si hubiera dos emplazamientos iguales en distintas configuraciones y así poder diferenciarlos.
