### ISSUE TITLE
#2837 Permite desactivar el Modo Estricto en canal radio Local FD

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#38]
Permite desactivar el Modo Estricto en canal radio Local FD

**Comment by Senttencya** [comment]
En Radio, en audio, siempre modo estricto

**Comment by agluque62** [comment]
Se ha comentado la posibilidad de 'desautorizar' este cambio y se ha desechado. La opción permanece como está. Por defecto se inicializa a 'Estricto' en radio y 'Normal' en Telefonía...
