### ISSUE TITLE
#2836 Las consultas en la solapa de comunicaciones del recurso radio Local, aleatoriamente muestran los colaterales o se presentan vacías (última versión 17/03/2017)

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#39]
Las consultas en la solapa de comunicaciones del recurso radio Local, aleatoriamente muestran los colaterales o se presentan vacías (última versión 17/03/2017)

**Comment by Senttencya** [comment]
Ya se encuentra solucionado. Aparecía un segundo signo '+' para el valor de la pestaña del primer colateral o equipamiento. Ahora debe aparecer el nombre con su configuración
