### ISSUE TITLE
#2319. Actualización de perfiles/roles Aplicaciones CFGR, CGRL y RCS2010-UG5KR

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#4]
Actualización de perfiles/roles Aplicaciones CFGR, CGRL y RCS2010-UG5KR
Ver apartado 3.0 del documento PCV-EPRS-002-00S (ESPECIFICACION FUNCIONAL CONTROL DE ACCESO, PRODUCTO GW ULISES G 5000R)

**Comment by Senttencya** [comment]
Parece que funciona pero hay que ver si cuadra con la especificación funcional del control de acceso.

**Comment by Senttencya** [comment]
Funcionando pero tengo que probarla mas y ver si de verdad "cuadran" las opciones que se muestran con la funcionalidad requerida
