### ISSUE TITLE
#2834  Permite crear canal Radio Local SIMPLE sin haber asignado URI-RX

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#41]
Permite crear canal Radio Local SIMPLE sin haber asignado URI-RX

**Comment by Senttencya** [comment]
Aunque faltan algunos detalles, ya se avisa de que se deben de rellenar esos campos

**Comment by Senttencya** [comment]
No funciona correctamente. Además hay que ampliarlo al resto de recursos que también utilizan URIs
