### ISSUE TITLE
#2833  No funciona correctamente los canales radio Local FD/Simple, no solo en cuanto a visualización, sino que al aplicar cambios, la pasarela Local FD/Simple no parece estar recibiendo la configuracion correcta

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#42]
No funciona correctamente los canales radio Local FD/Simple, no solo en cuanto a visualización, sino que al aplicar cambios, la pasarela Local FD/Simple no parece estar recibiendo la configuracion correcta

**Comment by Senttencya** [comment]
En local me funciona bien. Faltaría comprobar que se manda correctamente en el online.

**Comment by agluque62** [comment]
Hasta donde he podido probar, esto funciona también online
