### ISSUE TITLE
#2840. Error Intentando modificar la URI/tipo de un IF telefonico

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#44]
Intentando modificar la URI/tipo de un IF telefonico de un recurso, aparentemente la app te lo permite, pero una vez que picas CONFIRMAR vuelves a visualizar la configuración del recurso y no ha hecho caso al cambio que has intentado hacer.

**Comment by Senttencya** [comment]
A mi si me ha funcionado el modificar el campo URI para un recurso telefónico
