### ISSUE TITLE
#2843	Error al copiar una CONFIGURACIÓN

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#46]
Al copiar una CONFIGURACIÓN, el HMI muestra el pop de COPIA EN CURSO, y luego copia realizada, pero no refresca la zona donde se muestran las configuraciones existentes.
SIGUE PENDIENTE prohibir copias de config. con el mismo nombre.
SIGUE PENDIENTE comprobar que al borrar cualquiera de las repetida, se borran todas.

**Comment by Senttencya** [comment]
Comprobar.
