### ISSUE TITLE
#2334. PETICION. FUN09-1

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#5]
Control de Configuración. Es necesario que en el control de configuración de versión se incluyan los datos necesarios para que una vez cargado el software de las aplicaciones y tarjetas, el personal de Núcleo o el cliente, pueda verificar que el software cargado coincide con el que aparece en el control de configuración. Es imprescindible y necesario para el control de versiones en pruebas de validación y entrega de sistemas. En el caso de la aplicación CFGL existe una pestaña de versiones pero no coinciden los datos, la aplicación CFGR desconocemos donde se registra, el RCS la tiene pero no coinciden los datos que aparecen con el control de configuración y las tarjetas suministradas por fabrica se entregan sin etiqueta de del firmware y software cargado.

**Comment by Senttencya** [comment]
Se ha incluido una opción "Versión" dentro del menú principal de configuración, que al pulsarla muestra un listado de:
Versión, subversión, fecha (contenida en el fichero configUlises.json). Así como un hash MD5 y tamaño para cada uno de los ficheros que se incluyan en el apartado Ficheros del json anteriormente mencionado.

Ejemplo:
"Ulises": {
    "HistoricsDeep": 30,
    "LoginTimeOut": 0,
    "Region": "Región Centro",
    "BackupServiceDomain": "localhost:8082",
    "Version": "V 9.0",
    "SubVersion": "Beta 2",
    "Date": "03/02/2017",
    "Files": [
      {
        "Name": "app.js",
        "Path": "/"
      },
      {
        "Name": "package.json",
        "Path": "/"
      },
      {
        "Name": "configUlises.json",
        "Path": "/"
      }
    ]
  }
}
