### ISSUE TITLE
Asingancion ID de Tabla BSS a recurso.

### ISSUE THREAD

**Issue by agluque62** [NucleoDf/ug5k-redanserv-config#59]
Se ha observado (no se bajo que circunstancias) que una misma tabla_bss está asignada 2 veces ?? al mismo recurso. Esto se traduce en que los valores recibidos por la pasarela están duplicados y no puede generar de forma correcta la funcion de transformación correspondiente.

**Comment by Senttencya** [comment]
Corregido. Eliminada la referencia a AddRadioParameters
